export const USERS_TYPES = {
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  EDIT_USER_PROFILE_FAILURE: 'EDIT_USER_PROFILE_FAILURE',
  EDIT_USER_PROFILE_SUCCESS: 'EDIT_USER_PROFILE_SUCCESS',
  EDIT_USER_PROFILE_REQUEST: 'EDIT_USER_PROFILE_REQUEST',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
};
