export const AUTH_TYPES = {
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  FORGET_PASSWORD_FAILURE: 'FORGET_PASSWORD_FAILURE',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_REQUEST: 'FORGET_PASSWORD_REQUEST',
  LOGOUT: 'LOGOUT',
};
